name: gexxx_flutter
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter



  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  http: ^0.12.0+4
  
  auto_size_text: ^2.1.0  
  flutter_svg: ^0.17.3+1
  firebase_auth: ^0.15.0+1
  provider: ^3.1.0
  flutter_spinkit: "^4.1.2"
  curved_navigation_bar: ^0.3.2
  cloud_firestore: ^0.12.10
  translator: ^0.1.1
  location: ^2.4.0
  pin_code_text_field: ^1.5.1
  bottom_navy_bar: ^5.4.0
  fluttertoast: ^3.0.0
  dynamic_theme: ^1.0.0
  geolocator: ^5.1.1
  weather_icons: ^2.0.1



dev_dependencies:
  flutter_test:
    sdk: flutter

    

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  assets:
      - Phone_code/Phone_code.json
      - State_names/State_names.json
      - Crop_database/crop_database.json
      - assets/images/wheat1.jpg
      - assets/images/maize1.jpg
      - assets/images/bajra1.jpg
      - assets/images/wheat2.jpg
      - assets/images/bajra2.jpg
      - assets/images/maize2.jpg
      - assets/images/wheat3.jpg
      - assets/images/bajra2.jpg
      - assets/images/maize3.jpg
      - assets/images/cloudy.png
      - assets/images/clearsky.png
      - assets/images/rain.png
      - assets/images/haze.png
      - assets/images/drizzle.png
      - assets/images/dust.png
      - assets/images/mist.png
      - assets/images/sand.png
      - assets/images/smoke.png
      - assets/images/snow.png
      - assets/images/tunderstrom.png
      - lib/languages/en.JSON
      - lib/languages/hi.JSON

  fonts:
    - family: Circular
      fonts:
        - asset: assets/fonts/CircularStd-Medium.ttf
        - asset: assets/fonts/CircularAir-Light.ttf
          weight: 100
        - asset: assets/fonts/CircularStd-Bold.ttf
          weight: 500
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans.ttf


  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
